### ISSUE TITLE
Task2.4-Generate data for 1 stage addition

### ISSUE THREAD

**Issue by YuhaoDuuu** [AguaClara/2_stage_coag_addition#1]
In each single circulation, the coag dosage is: 0.5, 1, 1.5, 2.0, 2.5. Actually this is the value used by Yingda(Author of our reference thesis). My point is that we should add two more data point, one between 1-1.5, and the other between 1.5-2.0. Because usually we generate desirable effluent turbidity around that range, besides, we might don't have to start from 0.5mg/L, for that value is too low to treat the raw water.
My plan is that we run 3 circulation per week, basically that will take 3 days, we use different humic acid between those 3 diff tirals within a week. Thus we can test the impact of both humic acid and coagulant dosage on the flocculate process.

**Comment by cp546** [comment]
Issue is combined with Task 3.1.
