### ISSUE TITLE
Task 3.1 -  Fix Leaks in apparatus

### ISSUE THREAD

**Issue by babsorams** [AguaClara/2_stage_coag_addition#16]
Fix Leaks

**Comment by babsorams** [comment]
The T connection hat mixes the raw water and clay water is experiencing major leaks. We believe that this may be due to a connection that is open to the atmosphere that is reducing the pressure in our system. This also results in lack of pressure in our contact chambers causing them to not fill up with water. In addition, our influent turbidimeter is experiencing either a leakage or blockage which is also interfering with the overall pressure of our system.

**Comment by cp546** [comment]
The water flowing in and out of the turbidity meter is very different. Water flowing out is not half as much as water flowing in.

**Comment by YuhaoDuuu** [comment]
On Friday, March 2nd, met with Monroe in the lab, we fixed the leak by cutting the erosion part of the tubes, and successfully ran the apparatus without any significant leak。

**Comment by YuhaoDuuu** [comment]
![img_1941](https://user-images.githubusercontent.com/31321323/36922117-d93e7090-1e34-11e8-8387-01eeeed03b37.JPG)
This is what the tripple connection looks like right now.

**Comment by YuhaoDuuu** [comment]
![img_0420](https://user-images.githubusercontent.com/31321323/36922162-f9d21604-1e34-11e8-9510-66f5dc8d888e.JPG)
This is what the tripple connection used to be.
