### ISSUE TITLE
Task2.5 - 2 stages addition experiment

### ISSUE THREAD

**Issue by YuhaoDuuu** [AguaClara/2_stage_coag_addition#2]
Carry on series of control experiment for 2 stages addition, find the most effective portion of coagulant allocation. Then compare with data generated from 1 stage experiment.

Two-stage coagulant addition experiment should base on the data we generate on the first week, the total amount coag addition can be the least dosage which can achieve the effluent requirement, and then we add two more circulations for comparison, vary the total amount, +-0.5 on the basis of the first trial. During those weeks we conduct two stages addition, we won’t test the effect of humic acid on flocculation because the mechanism of this part should be similar between one and two stage.

**Comment by cp546** [comment]
Issue is combined with Task3.3 - Generate Data for 2 stage addition
