### ISSUE TITLE
Order Humic Acid

### ISSUE THREAD

**Issue by ChingPangggg** [AguaClara/2_stage_coag_addition#33]
@monroews @caseyching13 Hi Monroe, hi Casey, our group can not find the HA in the lab since yesterday. Can we order some of it?

**Comment by monroews** [comment]
@JonathanDavidHarris I found the humic acid in the teaching lab and returned it to the cabinet in the AguaClara lab. If the teaching lab needs some, please just take a small container of humic acid (labeled) to the teaching lab!
